### PR TITLE
Added .clang-format and applied the clang-format tool to all .c and .…

### PR DESCRIPTION
**Pull request by ckaran**
Added .clang-format and applied the [clang-format](http://clang.llvm.org/docs/ClangFormat.html) tool to all .c and .h files.

[clang-format](http://clang.llvm.org/docs/ClangFormat.html) is a tool for automatically formatting C/C++/Obj-C code.  This allows a project to define a formatting style that is applied across the entire project, which can make it much easier to read.  I've added the .clang-format file at the root of the project which can be modified to control the styles used.  I've also formatted all .c and .h files using clang-format and the style in this commit.

### CODE REVIEW

**Comment by ckaran** [comment]
OK, this is the first time I've had clang-format emit failing code.  I'm going to withdraw this pull request and work on figuring out what went wrong.

**Comment by jplevyak** [comment]
There are a couple issues.  The first is that this is old C code and so it
doesn't obey the typical modern rules, in particular all the headers are
not #ifdef protected, and do not include their dependencies, instead there
is a single header "d.h" which everyone is supposed to include which
handles the dependencies explicitly.   This is a problem because
clang-format likes to reorder headers alphabetically.  The generated code
also uses #ifndef XXX to allow XXX to be overridden which also depends on
header order.  The second problem is that add_array_member is using
stringification in the preprocessor with strings of the form 0x%x which
clang-format incorrectly interprets as 0x % x instead of as a token which
will be stringified.

These issues could be fixed.   The latter is a bit annoying because it is a
arguably a bug in clang-format.

**Comment by ckaran** [comment]
That would explain quite a bit.  I've started working on individual files, getting them through clang-format.  

I could also make modifications to the code outside of clang-format, but that will mean that the branch will have a LOT of weird intermingled changes that aren't related to clang-format directly.  Will that bother you?  If not, I'll keep on banging on this branch until it all works.

**Comment by ckaran** [comment]
No problem, I went ahead and merged in the changes.  

On a separate note, is it OK if we switch to using [clang](http://clang.llvm.org/) as the compiler?  The only copy of gcc that I have is ancient, and I can't easily upgrade it currently, but I have a modern version of clang (I know that is a poor excuse for switching compilers, but I'm really kind of stuck right now).

**Comment by jplevyak** [comment]
Sure.  It should work with both. Make it use CC in the environment if it is
available.

**Comment by ckaran** [comment]
Actually, my plan is just to make the change temporarily; assuming you're OK with it, I'd like to move it to using [cmake](https://cmake.org/) so that we can get build files for multiple build systems (I personally prefer [ninja](https://ninja-build.org/) because of how fast it is, and cmake generates ninja files).  That move will be in another branch at another time though.

BTW, I vaguely remember seeing a comment in the code saying that using tables were slow, and that there were some speedups that you were planning on including.  Is that still a part of the plan?

**Pull request closed without merging**
