### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by ckaran**
This may be a headache.  I've discovered that sometimes the code passes all tests, and sometimes it doesn't **even though no changes were made to the code.** I strongly suspect that there is a reference to uninitialized memory somewhere that sometimes works and sometimes doesn't.  As a test do the following:

```
make && make test
git clean -xdf
make && make test
```

If you get the same results I do, then the first time will fail, but the second time will succeed.  This is fairly consistent, which means that bad things are happening somewhere deep in the code.  I don't know if you want to reject this request, but I do suggest grabbing a copy of my repository and seeing if you get the same results as I am.

### CODE REVIEW

**Comment by ckaran** [comment]
@jplevyak You can probably merge this into your code at this point.  The only file that I'm having a hard time with is `write_tables.c`; everything else works.  In particular, I was able to kill off the `missing initializers` warnings, which means that the tests are now deterministic.  I also was able to regenerate the committed `grammar.g.c` file from the built `make_dparser` executable in the directory, so everything seems to be working reasonably well.  Would you be willing to work on getting `write_tables.c` working with `clang-format`?  It's the last C file that can't be fed through it safely, and I'm going to be too busy for the next while to look at it.

**Comment by ckaran** [comment]
OK, I figured out what was causing the hangups with `write_tables.c`, and fixed them.  As a result `clang-format` now works; I ran it on all `.h` and `.c` files, and ran all the tests.

In addition, I add a `.clang-tidy` file for [clang-tidy](http://clang.llvm.org/extra/clang-tidy/), and ran it on all the .c files, so all the statements that didn't have braces now do.  That is:
```C
if (a)
    return blah;
```

is now

```C
if (a)
{
    return blah;
}
```

That said, there are still a lot of warnings when you use `-Wextra -pedantic -c11` as the set of flags.  I don't have time right now to go through all of them, and this branch isn't the right place for them anyways (it should have only contained `clang-format` related code).  Once you've pulled all the outstanding pull requests, can you let me know?  I'll delete all those branches and get to work on the other stuff.  Until then I'm going to work on other projects.

**Comment by jplevyak** [comment]
I'll put it under valgrind and see if I can find it.

**Comment by jplevyak** [comment]
IMO brackets should follow the if:

if (a) {
  foo();
}

and single lines should follow as well without brackets:

if (a) foo();

**Comment by ckaran** [comment]
I see where you're coming from, but I disagree.  I've had a few too many cases switching between Python and C where I forget that whitespace doesn't indicate which statement a block is a part of.  Explicitly putting in braces everywhere really makes it clear what a block belongs to.

As for the brace following the `if`, or being on a separate line, I personally prefer it on a separate line, but I can edit the `.clang-format` file so that it puts it on the same line.  Do you want me to go ahead and do so, or do you want to do it?

Also, has anything shaken out of `valgrind` yet?

**Comment by jplevyak** [comment]
Formatted in a different commit.

**Pull request closed without merging**
